Repository Rebooting-Me/Home-Maintainence-Service, pull requests merged in 2023-02, with the labels that each got.

#58 Stry 4 issue 55 integration
  .eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/assets/homeowner-r.svg
  client/src/components/footer/Footer.jsx
  client/src/components/footer/Footer.module.css
  client/src/components/landing/Features/Features.module.css
  client/src/components/landing/HomeownerComment/HomeownerComment.jsx
  client/src/components/landing/HomeownerComment/HomeownerComment.module.css
  client/src/components/landing/Landing.js
  client/src/components/signin/Form/Form.jsx
  client/src/components/signin/Form/Form.module.css
  client/src/components/signup/Form/Form.jsx
  client/src/components/signup/Form/Form.module.css
  client/src/context/AuthContext.js
  client/src/hooks/useAuthContext.js
  client/src/hooks/useSignin.js
  client/src/hooks/useSignout.js
  client/src/hooks/useSignup.js
  client/src/index.js
  client/src/pages/Landing.jsx
  client/src/pages/Signin.jsx
  client/src/pages/Signup.jsx
  package-lock.json
  package.json
Labels: task

#64 Stry 4 issue 55 integration
  client/src/assets/contractor-r.svg
  client/src/assets/contractor/carlos.png
  client/src/assets/contractor/roberto.png
  client/src/assets/rightdown.svg
  client/src/assets/service.svg
  client/src/components/landing/About/About.jsx
  client/src/components/landing/About/About.module.css
  client/src/components/landing/ContractorComment/ContractorComment.jsx
  client/src/components/landing/ContractorComment/ContractorComment.module.css
  client/src/components/landing/Hero/Hero.jsx
  client/src/components/landing/Hero/Hero.module.css
  client/src/components/signup/Form/Form.jsx
  client/src/constants/contractorComments.js
  client/src/pages/Landing.jsx
Labels: task

#82 Stry 6 homeowner create listing
  backend/controllers/newListingController.js
  backend/controllers/userController.js
  backend/middleware/homeOwnerAuth.js
  backend/models/contractorModel.js
  backend/models/helper.js
  backend/models/homeownerModel.js
  backend/models/listingModel.js
  backend/models/services.js
  backend/routes/newListing.js
  backend/server.js
  client/package.json
  package-lock.json
Labels: user story, task

#83 Task 66 standalone listing backend
  backend/controllers/getListingController.js
  backend/models/contractorModel.js
  backend/models/helper.js
  backend/routes/getListing.js
  backend/server.js
Labels: user story, task

#84 Task 66 standalone listing backend
  backend/models/contractorModel.js
Labels: task

#86 Migrated tests to Mocha for backend
  backend/controllers/newListingController.js
  backend/jest.config.js
  backend/package-lock.json
  backend/package.json
  backend/test/contractor.test.js
  backend/test/login.test.js
  backend/test/newListing.test.js
  backend/test/rootHooks.js
  backend/test/signup.test.js
  backend/test/testUtils.js
  backend/tests/contractor.test.js
  backend/tests/newListing.test.js
  backend/tests/signup.test.js
  package.json
Labels: enhancement

#89 Task 69 multiple listings backend
  backend/app.js
  backend/controllers/contractorController.js
  backend/routes/contractor.js
  backend/server.js
Labels: enhancement, task
