Repository Rebooting-Me/Home-Maintainence-Service, pull requests merged in 2023-03, with the labels that each got.

#102 Stry8 contractor listings backend
  backend/.env
  backend/constants.js
  backend/controllers/contractorController.js
  backend/controllers/getListingController.js
  backend/controllers/userController.js
  backend/db.js
  backend/middleware/requireAuth.js
  backend/models/contractorModel.js
  backend/models/helper.js
  backend/models/homeownerModel.js
  backend/models/listingModel.js
  backend/routes/contractor.js
  backend/routes/getListing.js
  backend/routes/newListing.js
  backend/test/contractor.test.js
  backend/test/getListing.test.js
  backend/test/login.test.js
  backend/test/newListing.test.js
  backend/test/signup.test.js
  client/setupProxy.js
Labels: task

#105 Task 68 multiple listings implementation
  backend/models/listingModel.js
  client/src/components/dashboard/contractor/Dashboard/Dashboard.jsx
  client/src/components/dashboard/contractor/Dashboard/Dashboard.module.css
  client/src/components/dashboard/contractor/Sidebar/Sidebar.jsx
  client/src/components/listings/Filter.svg
  client/src/components/listings/Listings.jsx
  client/src/components/listings/Listings.module.css
  client/src/components/listings/ServiceIcon.jsx
  client/src/components/listings/icons/electrical.svg
  client/src/components/listings/icons/landscaping.svg
  client/src/components/listings/icons/pest.svg
  client/src/components/listings/icons/plumbing.svg
  client/src/components/listings/icons/remodeling.svg
  client/src/components/listings/icons/roofing.svg
  client/src/components/listings/image.svg
  client/src/pages/ContractorDashboard.jsx
Labels: enhancement, task

#104 Frontend testing setup
  client/package-lock.json
  client/package.json
  client/src/App.test.js
  client/src/components/signin/Form/Form.jsx
  client/src/components/signup/Form/Form.jsx
  client/src/constants/testingConstants.js
  client/src/mocks/mockFetchSignUp.js
  client/src/tests/contractorSignup.test.js
  client/src/tests/homeownerSignup.test.js
  client/src/tests/landingPage.test.js
Labels: enhancement

#106 Task 75 contractor profile implementation
  backend/app.js
  backend/controllers/contractorController.js
  backend/controllers/servicesController.js
  backend/models/contractorModel.js
  backend/routes/getServices.js
  client/package-lock.json
  client/package.json
  client/src/assets/pest_control.svg
  client/src/components/ServicesButtonGroup/ServicesButtonGroup.jsx
  client/src/components/dashboard/contractor/Dashboard/Dashboard.jsx
  client/src/components/dashboard/contractor/Dashboard/Dashboard.module.css
  client/src/components/dashboard/contractor/Profile/Profile
  client/src/components/dashboard/contractor/Profile/Profile.jsx
  client/src/components/dashboard/contractor/Profile/Profile.module.css
  client/src/components/dashboard/contractor/Profile/ProfileEdit.jsx
  client/src/components/dashboard/contractor/Profile/ProfileView.jsx
  client/src/components/dashboard/contractor/Sidebar/Sidebar.jsx
  client/src/components/dashboard/homeowner/Projects/NewProjectForm/NewProjectForm.jsx
  client/src/components/dashboard/homeowner/Projects/NewProjectForm/NewProjectForm.module.css
  client/src/components/dashboard/homeowner/Projects/Projects.jsx
  client/src/constants/features.js
  client/src/constants/profileHolder.js
  client/src/context/ProfileContext.js
  client/src/hooks/useCreateProject.js
  client/src/hooks/useProfileContext.js
  client/src/hooks/useServices.js
  client/src/index.js
Labels: task

#114 Backend edit listing
  backend/app.js
  backend/constants.js
  backend/controllers/homeownerController.js
  backend/controllers/listingController.js
  backend/controllers/newListingController.js
  backend/models/helper.js
  backend/routes/contractorRoutes.js
  backend/routes/getListing.js
  backend/routes/homeownerRoutes.js
  backend/routes/listingRoutes.js
  backend/routes/newListing.js
  backend/test/contractor.test.js
  backend/test/getListing.test.js
  backend/test/listing.test.js
  backend/test/newListing.test.js
Labels: enhancement, task

#115 Contractor filters
  backend/controllers/homeownerController.js
  backend/routes/contractorRoutes.js
  backend/routes/homeownerRoutes.js
  backend/test/contractor.test.js
Labels: enhancement

#120 Frontend testing continuation
  client/jest.config.js
  client/package-lock.json
  client/package.json
  client/src/components/signin/Form/Form.jsx
  client/src/constants/testingConstants.js
  client/src/context/AuthContext.js
  client/src/tests/contractorDashboard.test.js
  client/src/tests/contractorSignin.test.js
  client/src/tests/contractorSignup.test.js
  client/src/tests/homeownerDashboard.test.js
  client/src/tests/homeownerSignin.test.js
  client/src/tests/homeownerSignup.test.js
Labels: task
